// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.example.tutorial.protos;

public interface TestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Test)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 2;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string str = 3;</code>
   * @return The str.
   */
  java.lang.String getStr();
  /**
   * <code>string str = 3;</code>
   * @return The bytes for str.
   */
  com.google.protobuf.ByteString
      getStrBytes();

  /**
   * <code>repeated int32 arrays = 4;</code>
   * @return A list containing the arrays.
   */
  java.util.List<java.lang.Integer> getArraysList();
  /**
   * <code>repeated int32 arrays = 4;</code>
   * @return The count of arrays.
   */
  int getArraysCount();
  /**
   * <code>repeated int32 arrays = 4;</code>
   * @param index The index of the element to return.
   * @return The arrays at the given index.
   */
  int getArrays(int index);

  /**
   * <code>int32 max = 536870911;</code>
   * @return The max.
   */
  int getMax();
}
