// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_syntax.proto

package com.zddhub.proto;

public interface AuthorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Author)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 2;</code>
   * @return The age.
   */
  int getAge();

  /**
   * <code>string blog = 3;</code>
   * @return The blog.
   */
  String getBlog();
  /**
   * <code>string blog = 3;</code>
   * @return The bytes for blog.
   */
  com.google.protobuf.ByteString
      getBlogBytes();

  /**
   * <code>double income = 4;</code>
   * @return The income.
   */
  double getIncome();
}
