// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_syntax.proto

package com.zddhub.proto;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 3. Define field id, its type is int32. Use minimum field number(1)
   * </pre>
   *
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <pre>
   * 4. Define string
   * </pre>
   *
   * <code>string str = 3;</code>
   * @return The str.
   */
  String getStr();
  /**
   * <pre>
   * 4. Define string
   * </pre>
   *
   * <code>string str = 3;</code>
   * @return The bytes for str.
   */
  com.google.protobuf.ByteString
      getStrBytes();

  /**
   * <pre>
   * 5. Define int64 arrays，length &gt;= 0
   * </pre>
   *
   * <code>repeated int64 arrays = 4;</code>
   * @return A list containing the arrays.
   */
  java.util.List<Long> getArraysList();
  /**
   * <pre>
   * 5. Define int64 arrays，length &gt;= 0
   * </pre>
   *
   * <code>repeated int64 arrays = 4;</code>
   * @return The count of arrays.
   */
  int getArraysCount();
  /**
   * <pre>
   * 5. Define int64 arrays，length &gt;= 0
   * </pre>
   *
   * <code>repeated int64 arrays = 4;</code>
   * @param index The index of the element to return.
   * @return The arrays at the given index.
   */
  long getArrays(int index);

  /**
   * <code>.Message.Answer answer = 16;</code>
   * @return The enum numeric value on the wire for answer.
   */
  int getAnswerValue();
  /**
   * <code>.Message.Answer answer = 16;</code>
   * @return The answer.
   */
  Message.Answer getAnswer();

  /**
   * <code>.Message.InnerMessage inner_message = 300;</code>
   * @return Whether the innerMessage field is set.
   */
  boolean hasInnerMessage();
  /**
   * <code>.Message.InnerMessage inner_message = 300;</code>
   * @return The innerMessage.
   */
  Message.InnerMessage getInnerMessage();
  /**
   * <code>.Message.InnerMessage inner_message = 300;</code>
   */
  Message.InnerMessageOrBuilder getInnerMessageOrBuilder();

  /**
   * <pre>
   *     OneOf messages can't be repeated.
   * </pre>
   *
   * <code>bool is_true = 5;</code>
   * @return Whether the isTrue field is set.
   */
  boolean hasIsTrue();
  /**
   * <pre>
   *     OneOf messages can't be repeated.
   * </pre>
   *
   * <code>bool is_true = 5;</code>
   * @return The isTrue.
   */
  boolean getIsTrue();

  /**
   * <pre>
   * 13. bytes
   * </pre>
   *
   * <code>bytes bytes = 6;</code>
   * @return Whether the bytes field is set.
   */
  boolean hasBytes();
  /**
   * <pre>
   * 13. bytes
   * </pre>
   *
   * <code>bytes bytes = 6;</code>
   * @return The bytes.
   */
  com.google.protobuf.ByteString getBytes();

  /**
   * <pre>
   * 14. Use maximum field number.
   * </pre>
   *
   * <code>int32 max_field_number = 536870911;</code>
   * @return The maxFieldNumber.
   */
  int getMaxFieldNumber();

  public Message.TestOneofCase getTestOneofCase();
}
