// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_syntax.proto

package com.zddhub.proto;

/**
 * <pre>
 * 2. Define data struct - message
 * </pre>
 *
 * Protobuf type {@code Message}
 */
public final class Message extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Message)
    MessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Message.newBuilder() to construct.
  private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Message() {
    str_ = "";
    arrays_ = emptyLongList();
    answer_ = 0;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new Message();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Message(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            str_ = s;
            break;
          }
          case 32: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              arrays_ = newLongList();
              mutable_bitField0_ |= 0x00000001;
            }
            arrays_.addLong(input.readInt64());
            break;
          }
          case 34: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
              arrays_ = newLongList();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              arrays_.addLong(input.readInt64());
            }
            input.popLimit(limit);
            break;
          }
          case 40: {
            testOneofCase_ = 5;
            testOneof_ = input.readBool();
            break;
          }
          case 50: {
            testOneofCase_ = 6;
            testOneof_ = input.readBytes();
            break;
          }
          case 128: {
            int rawValue = input.readEnum();

            answer_ = rawValue;
            break;
          }
          case 2402: {
            InnerMessage.Builder subBuilder = null;
            if (innerMessage_ != null) {
              subBuilder = innerMessage_.toBuilder();
            }
            innerMessage_ = input.readMessage(InnerMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(innerMessage_);
              innerMessage_ = subBuilder.buildPartial();
            }

            break;
          }
          case -8: {

            maxFieldNumber_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        arrays_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ProtoSyntax.internal_static_Message_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ProtoSyntax.internal_static_Message_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Message.class, Builder.class);
  }

  /**
   * <pre>
   * 6. Define enum
   * </pre>
   *
   * Protobuf enum {@code Message.Answer}
   */
  public enum Answer
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 7. The first number of enum field must be 0
     * </pre>
     *
     * <code>YES = 0;</code>
     */
    YES(0),
    /**
     * <code>NO = 1;</code>
     */
    NO(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 7. The first number of enum field must be 0
     * </pre>
     *
     * <code>YES = 0;</code>
     */
    public static final int YES_VALUE = 0;
    /**
     * <code>NO = 1;</code>
     */
    public static final int NO_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static Answer valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Answer forNumber(int value) {
      switch (value) {
        case 0: return YES;
        case 1: return NO;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Answer>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Answer> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Answer>() {
            public Answer findValueByNumber(int number) {
              return Answer.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return Message.getDescriptor().getEnumTypes().get(0);
    }

    private static final Answer[] VALUES = values();

    public static Answer valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Answer(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Message.Answer)
  }

  public interface InnerMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Message.InnerMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 9. Define test_float. New message, field number can start from 1 again.
     * </pre>
     *
     * <code>float test_float = 1;</code>
     * @return The testFloat.
     */
    float getTestFloat();

    /**
     * <pre>
     * 10. Define map
     * </pre>
     *
     * <code>map&lt;string, string&gt; map = 2;</code>
     */
    int getMapCount();
    /**
     * <pre>
     * 10. Define map
     * </pre>
     *
     * <code>map&lt;string, string&gt; map = 2;</code>
     */
    boolean containsMap(
        String key);
    /**
     * Use {@link #getMapMap()} instead.
     */
    @Deprecated
    java.util.Map<String, String>
    getMap();
    /**
     * <pre>
     * 10. Define map
     * </pre>
     *
     * <code>map&lt;string, string&gt; map = 2;</code>
     */
    java.util.Map<String, String>
    getMapMap();
    /**
     * <pre>
     * 10. Define map
     * </pre>
     *
     * <code>map&lt;string, string&gt; map = 2;</code>
     */

    String getMapOrDefault(
        String key,
        String defaultValue);
    /**
     * <pre>
     * 10. Define map
     * </pre>
     *
     * <code>map&lt;string, string&gt; map = 2;</code>
     */

    String getMapOrThrow(
        String key);
  }
  /**
   * <pre>
   * 8. Define nested message
   * </pre>
   *
   * Protobuf type {@code Message.InnerMessage}
   */
  public static final class InnerMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Message.InnerMessage)
      InnerMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use InnerMessage.newBuilder() to construct.
    private InnerMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InnerMessage() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new InnerMessage();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private InnerMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {

              testFloat_ = input.readFloat();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                map_ = com.google.protobuf.MapField.newMapField(
                    MapDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<String, String>
              map__ = input.readMessage(
                  MapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              map_.getMutableMap().put(
                  map__.getKey(), map__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoSyntax.internal_static_Message_InnerMessage_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoSyntax.internal_static_Message_InnerMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              InnerMessage.class, Builder.class);
    }

    public static final int TEST_FLOAT_FIELD_NUMBER = 1;
    private float testFloat_;
    /**
     * <pre>
     * 9. Define test_float. New message, field number can start from 1 again.
     * </pre>
     *
     * <code>float test_float = 1;</code>
     * @return The testFloat.
     */
    @Override
    public float getTestFloat() {
      return testFloat_;
    }

    public static final int MAP_FIELD_NUMBER = 2;
    private static final class MapDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          String, String> defaultEntry =
              com.google.protobuf.MapEntry
              .<String, String>newDefaultInstance(
                  ProtoSyntax.internal_static_Message_InnerMessage_MapEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        String, String> map_;
    private com.google.protobuf.MapField<String, String>
    internalGetMap() {
      if (map_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MapDefaultEntryHolder.defaultEntry);
      }
      return map_;
    }

    public int getMapCount() {
      return internalGetMap().getMap().size();
    }
    /**
     * <pre>
     * 10. Define map
     * </pre>
     *
     * <code>map&lt;string, string&gt; map = 2;</code>
     */

    @Override
    public boolean containsMap(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMapMap()} instead.
     */
    @Override
    @Deprecated
    public java.util.Map<String, String> getMap() {
      return getMapMap();
    }
    /**
     * <pre>
     * 10. Define map
     * </pre>
     *
     * <code>map&lt;string, string&gt; map = 2;</code>
     */
    @Override

    public java.util.Map<String, String> getMapMap() {
      return internalGetMap().getMap();
    }
    /**
     * <pre>
     * 10. Define map
     * </pre>
     *
     * <code>map&lt;string, string&gt; map = 2;</code>
     */
    @Override

    public String getMapOrDefault(
        String key,
        String defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * 10. Define map
     * </pre>
     *
     * <code>map&lt;string, string&gt; map = 2;</code>
     */
    @Override

    public String getMapOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetMap().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (testFloat_ != 0F) {
        output.writeFloat(1, testFloat_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetMap(),
          MapDefaultEntryHolder.defaultEntry,
          2);
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (testFloat_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, testFloat_);
      }
      for (java.util.Map.Entry<String, String> entry
           : internalGetMap().getMap().entrySet()) {
        com.google.protobuf.MapEntry<String, String>
        map__ = MapDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, map__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof InnerMessage)) {
        return super.equals(obj);
      }
      InnerMessage other = (InnerMessage) obj;

      if (Float.floatToIntBits(getTestFloat())
          != Float.floatToIntBits(
              other.getTestFloat())) return false;
      if (!internalGetMap().equals(
          other.internalGetMap())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TEST_FLOAT_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getTestFloat());
      if (!internalGetMap().getMap().isEmpty()) {
        hash = (37 * hash) + MAP_FIELD_NUMBER;
        hash = (53 * hash) + internalGetMap().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static InnerMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static InnerMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static InnerMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static InnerMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static InnerMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static InnerMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static InnerMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static InnerMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static InnerMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static InnerMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static InnerMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static InnerMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(InnerMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 8. Define nested message
     * </pre>
     *
     * Protobuf type {@code Message.InnerMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Message.InnerMessage)
        InnerMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoSyntax.internal_static_Message_InnerMessage_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoSyntax.internal_static_Message_InnerMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                InnerMessage.class, Builder.class);
      }

      // Construct using com.zddhub.proto.Message.InnerMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        testFloat_ = 0F;

        internalGetMutableMap().clear();
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoSyntax.internal_static_Message_InnerMessage_descriptor;
      }

      @Override
      public InnerMessage getDefaultInstanceForType() {
        return InnerMessage.getDefaultInstance();
      }

      @Override
      public InnerMessage build() {
        InnerMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public InnerMessage buildPartial() {
        InnerMessage result = new InnerMessage(this);
        int from_bitField0_ = bitField0_;
        result.testFloat_ = testFloat_;
        result.map_ = internalGetMap();
        result.map_.makeImmutable();
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof InnerMessage) {
          return mergeFrom((InnerMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(InnerMessage other) {
        if (other == InnerMessage.getDefaultInstance()) return this;
        if (other.getTestFloat() != 0F) {
          setTestFloat(other.getTestFloat());
        }
        internalGetMutableMap().mergeFrom(
            other.internalGetMap());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        InnerMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (InnerMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private float testFloat_ ;
      /**
       * <pre>
       * 9. Define test_float. New message, field number can start from 1 again.
       * </pre>
       *
       * <code>float test_float = 1;</code>
       * @return The testFloat.
       */
      @Override
      public float getTestFloat() {
        return testFloat_;
      }
      /**
       * <pre>
       * 9. Define test_float. New message, field number can start from 1 again.
       * </pre>
       *
       * <code>float test_float = 1;</code>
       * @param value The testFloat to set.
       * @return This builder for chaining.
       */
      public Builder setTestFloat(float value) {
        
        testFloat_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 9. Define test_float. New message, field number can start from 1 again.
       * </pre>
       *
       * <code>float test_float = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTestFloat() {
        
        testFloat_ = 0F;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          String, String> map_;
      private com.google.protobuf.MapField<String, String>
      internalGetMap() {
        if (map_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              MapDefaultEntryHolder.defaultEntry);
        }
        return map_;
      }
      private com.google.protobuf.MapField<String, String>
      internalGetMutableMap() {
        onChanged();;
        if (map_ == null) {
          map_ = com.google.protobuf.MapField.newMapField(
              MapDefaultEntryHolder.defaultEntry);
        }
        if (!map_.isMutable()) {
          map_ = map_.copy();
        }
        return map_;
      }

      public int getMapCount() {
        return internalGetMap().getMap().size();
      }
      /**
       * <pre>
       * 10. Define map
       * </pre>
       *
       * <code>map&lt;string, string&gt; map = 2;</code>
       */

      @Override
      public boolean containsMap(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        return internalGetMap().getMap().containsKey(key);
      }
      /**
       * Use {@link #getMapMap()} instead.
       */
      @Override
      @Deprecated
      public java.util.Map<String, String> getMap() {
        return getMapMap();
      }
      /**
       * <pre>
       * 10. Define map
       * </pre>
       *
       * <code>map&lt;string, string&gt; map = 2;</code>
       */
      @Override

      public java.util.Map<String, String> getMapMap() {
        return internalGetMap().getMap();
      }
      /**
       * <pre>
       * 10. Define map
       * </pre>
       *
       * <code>map&lt;string, string&gt; map = 2;</code>
       */
      @Override

      public String getMapOrDefault(
          String key,
          String defaultValue) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, String> map =
            internalGetMap().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       * 10. Define map
       * </pre>
       *
       * <code>map&lt;string, string&gt; map = 2;</code>
       */
      @Override

      public String getMapOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, String> map =
            internalGetMap().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearMap() {
        internalGetMutableMap().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       * 10. Define map
       * </pre>
       *
       * <code>map&lt;string, string&gt; map = 2;</code>
       */

      public Builder removeMap(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        internalGetMutableMap().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @Deprecated
      public java.util.Map<String, String>
      getMutableMap() {
        return internalGetMutableMap().getMutableMap();
      }
      /**
       * <pre>
       * 10. Define map
       * </pre>
       *
       * <code>map&lt;string, string&gt; map = 2;</code>
       */
      public Builder putMap(
          String key,
          String value) {
        if (key == null) { throw new NullPointerException(); }
        if (value == null) { throw new NullPointerException(); }
        internalGetMutableMap().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       * 10. Define map
       * </pre>
       *
       * <code>map&lt;string, string&gt; map = 2;</code>
       */

      public Builder putAllMap(
          java.util.Map<String, String> values) {
        internalGetMutableMap().getMutableMap()
            .putAll(values);
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Message.InnerMessage)
    }

    // @@protoc_insertion_point(class_scope:Message.InnerMessage)
    private static final InnerMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new InnerMessage();
    }

    public static InnerMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InnerMessage>
        PARSER = new com.google.protobuf.AbstractParser<InnerMessage>() {
      @Override
      public InnerMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InnerMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InnerMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<InnerMessage> getParserForType() {
      return PARSER;
    }

    @Override
    public InnerMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int testOneofCase_ = 0;
  private Object testOneof_;
  public enum TestOneofCase
      implements com.google.protobuf.Internal.EnumLite,
          InternalOneOfEnum {
    IS_TRUE(5),
    BYTES(6),
    TESTONEOF_NOT_SET(0);
    private final int value;
    private TestOneofCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static TestOneofCase valueOf(int value) {
      return forNumber(value);
    }

    public static TestOneofCase forNumber(int value) {
      switch (value) {
        case 5: return IS_TRUE;
        case 6: return BYTES;
        case 0: return TESTONEOF_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public TestOneofCase
  getTestOneofCase() {
    return TestOneofCase.forNumber(
        testOneofCase_);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <pre>
   * 3. Define field id, its type is int32. Use minimum field number(1)
   * </pre>
   *
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  @Override
  public int getId() {
    return id_;
  }

  public static final int STR_FIELD_NUMBER = 3;
  private volatile Object str_;
  /**
   * <pre>
   * 4. Define string
   * </pre>
   *
   * <code>string str = 3;</code>
   * @return The str.
   */
  @Override
  public String getStr() {
    Object ref = str_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      str_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 4. Define string
   * </pre>
   *
   * <code>string str = 3;</code>
   * @return The bytes for str.
   */
  @Override
  public com.google.protobuf.ByteString
      getStrBytes() {
    Object ref = str_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      str_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ARRAYS_FIELD_NUMBER = 4;
  private com.google.protobuf.Internal.LongList arrays_;
  /**
   * <pre>
   * 5. Define int64 arrays，length &gt;= 0
   * </pre>
   *
   * <code>repeated int64 arrays = 4;</code>
   * @return A list containing the arrays.
   */
  @Override
  public java.util.List<Long>
      getArraysList() {
    return arrays_;
  }
  /**
   * <pre>
   * 5. Define int64 arrays，length &gt;= 0
   * </pre>
   *
   * <code>repeated int64 arrays = 4;</code>
   * @return The count of arrays.
   */
  public int getArraysCount() {
    return arrays_.size();
  }
  /**
   * <pre>
   * 5. Define int64 arrays，length &gt;= 0
   * </pre>
   *
   * <code>repeated int64 arrays = 4;</code>
   * @param index The index of the element to return.
   * @return The arrays at the given index.
   */
  public long getArrays(int index) {
    return arrays_.getLong(index);
  }
  private int arraysMemoizedSerializedSize = -1;

  public static final int ANSWER_FIELD_NUMBER = 16;
  private int answer_;
  /**
   * <code>.Message.Answer answer = 16;</code>
   * @return The enum numeric value on the wire for answer.
   */
  @Override public int getAnswerValue() {
    return answer_;
  }
  /**
   * <code>.Message.Answer answer = 16;</code>
   * @return The answer.
   */
  @Override public Answer getAnswer() {
    @SuppressWarnings("deprecation")
    Answer result = Answer.valueOf(answer_);
    return result == null ? Answer.UNRECOGNIZED : result;
  }

  public static final int INNER_MESSAGE_FIELD_NUMBER = 300;
  private InnerMessage innerMessage_;
  /**
   * <code>.Message.InnerMessage inner_message = 300;</code>
   * @return Whether the innerMessage field is set.
   */
  @Override
  public boolean hasInnerMessage() {
    return innerMessage_ != null;
  }
  /**
   * <code>.Message.InnerMessage inner_message = 300;</code>
   * @return The innerMessage.
   */
  @Override
  public InnerMessage getInnerMessage() {
    return innerMessage_ == null ? InnerMessage.getDefaultInstance() : innerMessage_;
  }
  /**
   * <code>.Message.InnerMessage inner_message = 300;</code>
   */
  @Override
  public InnerMessageOrBuilder getInnerMessageOrBuilder() {
    return getInnerMessage();
  }

  public static final int IS_TRUE_FIELD_NUMBER = 5;
  /**
   * <pre>
   *     OneOf messages can't be repeated.
   * </pre>
   *
   * <code>bool is_true = 5;</code>
   * @return Whether the isTrue field is set.
   */
  @Override
  public boolean hasIsTrue() {
    return testOneofCase_ == 5;
  }
  /**
   * <pre>
   *     OneOf messages can't be repeated.
   * </pre>
   *
   * <code>bool is_true = 5;</code>
   * @return The isTrue.
   */
  @Override
  public boolean getIsTrue() {
    if (testOneofCase_ == 5) {
      return (Boolean) testOneof_;
    }
    return false;
  }

  public static final int BYTES_FIELD_NUMBER = 6;
  /**
   * <pre>
   * 13. bytes
   * </pre>
   *
   * <code>bytes bytes = 6;</code>
   * @return Whether the bytes field is set.
   */
  @Override
  public boolean hasBytes() {
    return testOneofCase_ == 6;
  }
  /**
   * <pre>
   * 13. bytes
   * </pre>
   *
   * <code>bytes bytes = 6;</code>
   * @return The bytes.
   */
  @Override
  public com.google.protobuf.ByteString getBytes() {
    if (testOneofCase_ == 6) {
      return (com.google.protobuf.ByteString) testOneof_;
    }
    return com.google.protobuf.ByteString.EMPTY;
  }

  public static final int MAX_FIELD_NUMBER_FIELD_NUMBER = 536870911;
  private int maxFieldNumber_;
  /**
   * <pre>
   * 14. Use maximum field number.
   * </pre>
   *
   * <code>int32 max_field_number = 536870911;</code>
   * @return The maxFieldNumber.
   */
  @Override
  public int getMaxFieldNumber() {
    return maxFieldNumber_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (!getStrBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, str_);
    }
    if (getArraysList().size() > 0) {
      output.writeUInt32NoTag(34);
      output.writeUInt32NoTag(arraysMemoizedSerializedSize);
    }
    for (int i = 0; i < arrays_.size(); i++) {
      output.writeInt64NoTag(arrays_.getLong(i));
    }
    if (testOneofCase_ == 5) {
      output.writeBool(
          5, (boolean)((Boolean) testOneof_));
    }
    if (testOneofCase_ == 6) {
      output.writeBytes(
          6, (com.google.protobuf.ByteString) testOneof_);
    }
    if (answer_ != Answer.YES.getNumber()) {
      output.writeEnum(16, answer_);
    }
    if (innerMessage_ != null) {
      output.writeMessage(300, getInnerMessage());
    }
    if (maxFieldNumber_ != 0) {
      output.writeInt32(536870911, maxFieldNumber_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (!getStrBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, str_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < arrays_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(arrays_.getLong(i));
      }
      size += dataSize;
      if (!getArraysList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      arraysMemoizedSerializedSize = dataSize;
    }
    if (testOneofCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(
            5, (boolean)((Boolean) testOneof_));
    }
    if (testOneofCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(
            6, (com.google.protobuf.ByteString) testOneof_);
    }
    if (answer_ != Answer.YES.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(16, answer_);
    }
    if (innerMessage_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(300, getInnerMessage());
    }
    if (maxFieldNumber_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(536870911, maxFieldNumber_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Message)) {
      return super.equals(obj);
    }
    Message other = (Message) obj;

    if (getId()
        != other.getId()) return false;
    if (!getStr()
        .equals(other.getStr())) return false;
    if (!getArraysList()
        .equals(other.getArraysList())) return false;
    if (answer_ != other.answer_) return false;
    if (hasInnerMessage() != other.hasInnerMessage()) return false;
    if (hasInnerMessage()) {
      if (!getInnerMessage()
          .equals(other.getInnerMessage())) return false;
    }
    if (getMaxFieldNumber()
        != other.getMaxFieldNumber()) return false;
    if (!getTestOneofCase().equals(other.getTestOneofCase())) return false;
    switch (testOneofCase_) {
      case 5:
        if (getIsTrue()
            != other.getIsTrue()) return false;
        break;
      case 6:
        if (!getBytes()
            .equals(other.getBytes())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + STR_FIELD_NUMBER;
    hash = (53 * hash) + getStr().hashCode();
    if (getArraysCount() > 0) {
      hash = (37 * hash) + ARRAYS_FIELD_NUMBER;
      hash = (53 * hash) + getArraysList().hashCode();
    }
    hash = (37 * hash) + ANSWER_FIELD_NUMBER;
    hash = (53 * hash) + answer_;
    if (hasInnerMessage()) {
      hash = (37 * hash) + INNER_MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getInnerMessage().hashCode();
    }
    hash = (37 * hash) + MAX_FIELD_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getMaxFieldNumber();
    switch (testOneofCase_) {
      case 5:
        hash = (37 * hash) + IS_TRUE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIsTrue());
        break;
      case 6:
        hash = (37 * hash) + BYTES_FIELD_NUMBER;
        hash = (53 * hash) + getBytes().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Message parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Message parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Message parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Message parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Message parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Message parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Message parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Message parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Message parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Message parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Message parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Message parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Message prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 2. Define data struct - message
   * </pre>
   *
   * Protobuf type {@code Message}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Message)
      MessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoSyntax.internal_static_Message_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoSyntax.internal_static_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Message.class, Builder.class);
    }

    // Construct using com.zddhub.proto.Message.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      id_ = 0;

      str_ = "";

      arrays_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      answer_ = 0;

      if (innerMessageBuilder_ == null) {
        innerMessage_ = null;
      } else {
        innerMessage_ = null;
        innerMessageBuilder_ = null;
      }
      maxFieldNumber_ = 0;

      testOneofCase_ = 0;
      testOneof_ = null;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ProtoSyntax.internal_static_Message_descriptor;
    }

    @Override
    public Message getDefaultInstanceForType() {
      return Message.getDefaultInstance();
    }

    @Override
    public Message build() {
      Message result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public Message buildPartial() {
      Message result = new Message(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      result.str_ = str_;
      if (((bitField0_ & 0x00000001) != 0)) {
        arrays_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.arrays_ = arrays_;
      result.answer_ = answer_;
      if (innerMessageBuilder_ == null) {
        result.innerMessage_ = innerMessage_;
      } else {
        result.innerMessage_ = innerMessageBuilder_.build();
      }
      if (testOneofCase_ == 5) {
        result.testOneof_ = testOneof_;
      }
      if (testOneofCase_ == 6) {
        result.testOneof_ = testOneof_;
      }
      result.maxFieldNumber_ = maxFieldNumber_;
      result.testOneofCase_ = testOneofCase_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Message) {
        return mergeFrom((Message)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Message other) {
      if (other == Message.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getStr().isEmpty()) {
        str_ = other.str_;
        onChanged();
      }
      if (!other.arrays_.isEmpty()) {
        if (arrays_.isEmpty()) {
          arrays_ = other.arrays_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureArraysIsMutable();
          arrays_.addAll(other.arrays_);
        }
        onChanged();
      }
      if (other.answer_ != 0) {
        setAnswerValue(other.getAnswerValue());
      }
      if (other.hasInnerMessage()) {
        mergeInnerMessage(other.getInnerMessage());
      }
      if (other.getMaxFieldNumber() != 0) {
        setMaxFieldNumber(other.getMaxFieldNumber());
      }
      switch (other.getTestOneofCase()) {
        case IS_TRUE: {
          setIsTrue(other.getIsTrue());
          break;
        }
        case BYTES: {
          setBytes(other.getBytes());
          break;
        }
        case TESTONEOF_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Message parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Message) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int testOneofCase_ = 0;
    private Object testOneof_;
    public TestOneofCase
        getTestOneofCase() {
      return TestOneofCase.forNumber(
          testOneofCase_);
    }

    public Builder clearTestOneof() {
      testOneofCase_ = 0;
      testOneof_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private int id_ ;
    /**
     * <pre>
     * 3. Define field id, its type is int32. Use minimum field number(1)
     * </pre>
     *
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @Override
    public int getId() {
      return id_;
    }
    /**
     * <pre>
     * 3. Define field id, its type is int32. Use minimum field number(1)
     * </pre>
     *
     * <code>int32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 3. Define field id, its type is int32. Use minimum field number(1)
     * </pre>
     *
     * <code>int32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private Object str_ = "";
    /**
     * <pre>
     * 4. Define string
     * </pre>
     *
     * <code>string str = 3;</code>
     * @return The str.
     */
    public String getStr() {
      Object ref = str_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        str_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 4. Define string
     * </pre>
     *
     * <code>string str = 3;</code>
     * @return The bytes for str.
     */
    public com.google.protobuf.ByteString
        getStrBytes() {
      Object ref = str_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        str_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 4. Define string
     * </pre>
     *
     * <code>string str = 3;</code>
     * @param value The str to set.
     * @return This builder for chaining.
     */
    public Builder setStr(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      str_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 4. Define string
     * </pre>
     *
     * <code>string str = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearStr() {
      
      str_ = getDefaultInstance().getStr();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 4. Define string
     * </pre>
     *
     * <code>string str = 3;</code>
     * @param value The bytes for str to set.
     * @return This builder for chaining.
     */
    public Builder setStrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      str_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.LongList arrays_ = emptyLongList();
    private void ensureArraysIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        arrays_ = mutableCopy(arrays_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     * 5. Define int64 arrays，length &gt;= 0
     * </pre>
     *
     * <code>repeated int64 arrays = 4;</code>
     * @return A list containing the arrays.
     */
    public java.util.List<Long>
        getArraysList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(arrays_) : arrays_;
    }
    /**
     * <pre>
     * 5. Define int64 arrays，length &gt;= 0
     * </pre>
     *
     * <code>repeated int64 arrays = 4;</code>
     * @return The count of arrays.
     */
    public int getArraysCount() {
      return arrays_.size();
    }
    /**
     * <pre>
     * 5. Define int64 arrays，length &gt;= 0
     * </pre>
     *
     * <code>repeated int64 arrays = 4;</code>
     * @param index The index of the element to return.
     * @return The arrays at the given index.
     */
    public long getArrays(int index) {
      return arrays_.getLong(index);
    }
    /**
     * <pre>
     * 5. Define int64 arrays，length &gt;= 0
     * </pre>
     *
     * <code>repeated int64 arrays = 4;</code>
     * @param index The index to set the value at.
     * @param value The arrays to set.
     * @return This builder for chaining.
     */
    public Builder setArrays(
        int index, long value) {
      ensureArraysIsMutable();
      arrays_.setLong(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 5. Define int64 arrays，length &gt;= 0
     * </pre>
     *
     * <code>repeated int64 arrays = 4;</code>
     * @param value The arrays to add.
     * @return This builder for chaining.
     */
    public Builder addArrays(long value) {
      ensureArraysIsMutable();
      arrays_.addLong(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 5. Define int64 arrays，length &gt;= 0
     * </pre>
     *
     * <code>repeated int64 arrays = 4;</code>
     * @param values The arrays to add.
     * @return This builder for chaining.
     */
    public Builder addAllArrays(
        Iterable<? extends Long> values) {
      ensureArraysIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, arrays_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 5. Define int64 arrays，length &gt;= 0
     * </pre>
     *
     * <code>repeated int64 arrays = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearArrays() {
      arrays_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    private int answer_ = 0;
    /**
     * <code>.Message.Answer answer = 16;</code>
     * @return The enum numeric value on the wire for answer.
     */
    @Override public int getAnswerValue() {
      return answer_;
    }
    /**
     * <code>.Message.Answer answer = 16;</code>
     * @param value The enum numeric value on the wire for answer to set.
     * @return This builder for chaining.
     */
    public Builder setAnswerValue(int value) {
      
      answer_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.Message.Answer answer = 16;</code>
     * @return The answer.
     */
    @Override
    public Answer getAnswer() {
      @SuppressWarnings("deprecation")
      Answer result = Answer.valueOf(answer_);
      return result == null ? Answer.UNRECOGNIZED : result;
    }
    /**
     * <code>.Message.Answer answer = 16;</code>
     * @param value The answer to set.
     * @return This builder for chaining.
     */
    public Builder setAnswer(Answer value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      answer_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.Message.Answer answer = 16;</code>
     * @return This builder for chaining.
     */
    public Builder clearAnswer() {
      
      answer_ = 0;
      onChanged();
      return this;
    }

    private InnerMessage innerMessage_;
    private com.google.protobuf.SingleFieldBuilderV3<
        InnerMessage, InnerMessage.Builder, InnerMessageOrBuilder> innerMessageBuilder_;
    /**
     * <code>.Message.InnerMessage inner_message = 300;</code>
     * @return Whether the innerMessage field is set.
     */
    public boolean hasInnerMessage() {
      return innerMessageBuilder_ != null || innerMessage_ != null;
    }
    /**
     * <code>.Message.InnerMessage inner_message = 300;</code>
     * @return The innerMessage.
     */
    public InnerMessage getInnerMessage() {
      if (innerMessageBuilder_ == null) {
        return innerMessage_ == null ? InnerMessage.getDefaultInstance() : innerMessage_;
      } else {
        return innerMessageBuilder_.getMessage();
      }
    }
    /**
     * <code>.Message.InnerMessage inner_message = 300;</code>
     */
    public Builder setInnerMessage(InnerMessage value) {
      if (innerMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        innerMessage_ = value;
        onChanged();
      } else {
        innerMessageBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Message.InnerMessage inner_message = 300;</code>
     */
    public Builder setInnerMessage(
        InnerMessage.Builder builderForValue) {
      if (innerMessageBuilder_ == null) {
        innerMessage_ = builderForValue.build();
        onChanged();
      } else {
        innerMessageBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Message.InnerMessage inner_message = 300;</code>
     */
    public Builder mergeInnerMessage(InnerMessage value) {
      if (innerMessageBuilder_ == null) {
        if (innerMessage_ != null) {
          innerMessage_ =
            InnerMessage.newBuilder(innerMessage_).mergeFrom(value).buildPartial();
        } else {
          innerMessage_ = value;
        }
        onChanged();
      } else {
        innerMessageBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Message.InnerMessage inner_message = 300;</code>
     */
    public Builder clearInnerMessage() {
      if (innerMessageBuilder_ == null) {
        innerMessage_ = null;
        onChanged();
      } else {
        innerMessage_ = null;
        innerMessageBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Message.InnerMessage inner_message = 300;</code>
     */
    public InnerMessage.Builder getInnerMessageBuilder() {
      
      onChanged();
      return getInnerMessageFieldBuilder().getBuilder();
    }
    /**
     * <code>.Message.InnerMessage inner_message = 300;</code>
     */
    public InnerMessageOrBuilder getInnerMessageOrBuilder() {
      if (innerMessageBuilder_ != null) {
        return innerMessageBuilder_.getMessageOrBuilder();
      } else {
        return innerMessage_ == null ?
            InnerMessage.getDefaultInstance() : innerMessage_;
      }
    }
    /**
     * <code>.Message.InnerMessage inner_message = 300;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        InnerMessage, InnerMessage.Builder, InnerMessageOrBuilder>
        getInnerMessageFieldBuilder() {
      if (innerMessageBuilder_ == null) {
        innerMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            InnerMessage, InnerMessage.Builder, InnerMessageOrBuilder>(
                getInnerMessage(),
                getParentForChildren(),
                isClean());
        innerMessage_ = null;
      }
      return innerMessageBuilder_;
    }

    /**
     * <pre>
     *     OneOf messages can't be repeated.
     * </pre>
     *
     * <code>bool is_true = 5;</code>
     * @return Whether the isTrue field is set.
     */
    public boolean hasIsTrue() {
      return testOneofCase_ == 5;
    }
    /**
     * <pre>
     *     OneOf messages can't be repeated.
     * </pre>
     *
     * <code>bool is_true = 5;</code>
     * @return The isTrue.
     */
    public boolean getIsTrue() {
      if (testOneofCase_ == 5) {
        return (Boolean) testOneof_;
      }
      return false;
    }
    /**
     * <pre>
     *     OneOf messages can't be repeated.
     * </pre>
     *
     * <code>bool is_true = 5;</code>
     * @param value The isTrue to set.
     * @return This builder for chaining.
     */
    public Builder setIsTrue(boolean value) {
      testOneofCase_ = 5;
      testOneof_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *     OneOf messages can't be repeated.
     * </pre>
     *
     * <code>bool is_true = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsTrue() {
      if (testOneofCase_ == 5) {
        testOneofCase_ = 0;
        testOneof_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <pre>
     * 13. bytes
     * </pre>
     *
     * <code>bytes bytes = 6;</code>
     * @return Whether the bytes field is set.
     */
    public boolean hasBytes() {
      return testOneofCase_ == 6;
    }
    /**
     * <pre>
     * 13. bytes
     * </pre>
     *
     * <code>bytes bytes = 6;</code>
     * @return The bytes.
     */
    public com.google.protobuf.ByteString getBytes() {
      if (testOneofCase_ == 6) {
        return (com.google.protobuf.ByteString) testOneof_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }
    /**
     * <pre>
     * 13. bytes
     * </pre>
     *
     * <code>bytes bytes = 6;</code>
     * @param value The bytes to set.
     * @return This builder for chaining.
     */
    public Builder setBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  testOneofCase_ = 6;
      testOneof_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 13. bytes
     * </pre>
     *
     * <code>bytes bytes = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearBytes() {
      if (testOneofCase_ == 6) {
        testOneofCase_ = 0;
        testOneof_ = null;
        onChanged();
      }
      return this;
    }

    private int maxFieldNumber_ ;
    /**
     * <pre>
     * 14. Use maximum field number.
     * </pre>
     *
     * <code>int32 max_field_number = 536870911;</code>
     * @return The maxFieldNumber.
     */
    @Override
    public int getMaxFieldNumber() {
      return maxFieldNumber_;
    }
    /**
     * <pre>
     * 14. Use maximum field number.
     * </pre>
     *
     * <code>int32 max_field_number = 536870911;</code>
     * @param value The maxFieldNumber to set.
     * @return This builder for chaining.
     */
    public Builder setMaxFieldNumber(int value) {
      
      maxFieldNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 14. Use maximum field number.
     * </pre>
     *
     * <code>int32 max_field_number = 536870911;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxFieldNumber() {
      
      maxFieldNumber_ = 0;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Message)
  }

  // @@protoc_insertion_point(class_scope:Message)
  private static final Message DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Message();
  }

  public static Message getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Message>
      PARSER = new com.google.protobuf.AbstractParser<Message>() {
    @Override
    public Message parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Message(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Message> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Message> getParserForType() {
    return PARSER;
  }

  @Override
  public Message getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

