// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_syntax.proto

package com.zddhub.proto;

public final class ProtoSyntax {
  private ProtoSyntax() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_InnerMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_InnerMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_InnerMessage_MapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_InnerMessage_MapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Author_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Author_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022proto_syntax.proto\"\352\002\n\007Message\022\n\n\002id\030\001" +
      " \001(\005\022\013\n\003str\030\003 \001(\t\022\016\n\006arrays\030\004 \003(\003\022\037\n\006ans" +
      "wer\030\020 \001(\0162\017.Message.Answer\022-\n\rinner_mess" +
      "age\030\254\002 \001(\0132\025.Message.InnerMessage\022\021\n\007is_" +
      "true\030\005 \001(\010H\000\022\017\n\005bytes\030\006 \001(\014H\000\022\034\n\020max_fie" +
      "ld_number\030\377\377\377\377\001 \001(\005\032{\n\014InnerMessage\022\022\n\nt" +
      "est_float\030\001 \001(\002\022+\n\003map\030\002 \003(\0132\036.Message.I" +
      "nnerMessage.MapEntry\032*\n\010MapEntry\022\013\n\003key\030" +
      "\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\031\n\006Answer\022\007\n\003YE" +
      "S\020\000\022\006\n\002NO\020\001B\014\n\ntest_oneof\"A\n\006Author\022\014\n\004n" +
      "ame\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\022\014\n\004blog\030\003 \001(\t\022\016\n\006" +
      "income\030\004 \001(\001B!\n\020com.zddhub.protoB\013ProtoS" +
      "yntaxP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_descriptor,
        new String[] { "Id", "Str", "Arrays", "Answer", "InnerMessage", "IsTrue", "Bytes", "MaxFieldNumber", "TestOneof", });
    internal_static_Message_InnerMessage_descriptor =
      internal_static_Message_descriptor.getNestedTypes().get(0);
    internal_static_Message_InnerMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_InnerMessage_descriptor,
        new String[] { "TestFloat", "Map", });
    internal_static_Message_InnerMessage_MapEntry_descriptor =
      internal_static_Message_InnerMessage_descriptor.getNestedTypes().get(0);
    internal_static_Message_InnerMessage_MapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_InnerMessage_MapEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_Author_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Author_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Author_descriptor,
        new String[] { "Name", "Age", "Blog", "Income", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
